# Introduction to Numpy

NumPy (Numerical Python) is a fundamental library for numerical computing in Python. It provides support for arrays, matrices, and a collection of mathematical functions to operate on these data structures efficiently. NumPy is particularly useful for scientific computing and data analysis because it allows for operations on large multi-dimensional arrays and matrices with high performance, thanks to its implementation in C and Fortran.

### Key Features of NumPy:
- **N-dimensional array (`ndarray`)**: NumPy’s primary data structure is the `ndarray`, which allows for efficient storage and manipulation of large data sets in multiple dimensions (e.g., 1D, 2D, 3D arrays, etc.).
- **Mathematical Functions**: NumPy provides a wide range of mathematical operations, such as linear algebra functions, statistical functions, and random number generation.
- **Broadcasting**: This feature allows NumPy to perform element-wise operations on arrays of different shapes without explicitly reshaping them.
- **Integration with Other Libraries**: NumPy is often used alongside other scientific libraries like SciPy, Pandas, and Matplotlib, forming the foundation for scientific computing in Python.
- **Efficiency**: NumPy operations are generally faster and more memory-efficient compared to traditional Python lists due to its implementation in lower-level languages.

NumPy is widely used in data science, machine learning, engineering, and other fields where large-scale numerical computations are required.

- The first python data science library we will learn about is NumPy.
- Almost every data science library we learn is built on top of NumPy.
- Now, lets' explore what this notebook will cover and why it is important. 

### Notebook Goals
- Understanding Numpy.
- Creating arrarys with NumPy.
- Retrieve information from NumPy array through slicing and indexing.
- Learn basic NumPy operations.

## What is NumPy?
- It's a Python library for creating N-dims arrays.
- It has ability to quickly broadcast functions.
- Built-in linear algebra, statistical distributions, trigonometric and random number capabilities.

## Why use NumPy?
- While NumPy structures look similar to standard Python lists, they are much more efficient.
- The broadcasting capabilities are also extremely useful for quickly applying functions to our datasets.

# Let's get started! 
- Let's explore how to create Numpy arrarys
    - Transforming standard list
    - Built-in functions
    - Generating random data
- We will also discuss some key attributes of NumPy arrays.

# NumPy Array

In [2]:
!pip install numpy

   ---------------------------------------- 0.0/16.3 MB ? eta -:--:--
   --------- ------------------------------ 3.7/16.3 MB 18.2 MB/s eta 0:00:01
   -------------------- ------------------- 8.4/16.3 MB 20.0 MB/s eta 0:00:01
   -------------------------------- ------- 13.1/16.3 MB 21.1 MB/s eta 0:00:01
   ---------------------------------------- 16.3/16.3 MB 21.3 MB/s eta 0:00:00


In [3]:
import numpy as np

In [4]:
list1 = [10,20,30,40]

In [5]:
type(list1)

list

In [6]:
np.array(list1)

array([10, 20, 30, 40])

In [7]:
## Original list is not changed
list1

[10, 20, 30, 40]

# NumPy 1D-Array

In [8]:
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40])

In [9]:
type(arr1)

numpy.ndarray

# NumPy 2D-Array

In [10]:
## 2D MATRIX
mat1 = [[11,12,13],
        [14,15,16],
        [17,18,19]]

mat1

[[11, 12, 13], [14, 15, 16], [17, 18, 19]]

In [11]:
np.array(mat1)

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

# Built-in Methods to create arrays
There are lots of built-in ways to generate arrays.

## np.arange()

Return evenly spaced values within a given interval. [[Link](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]

In [12]:
## Let's use inbuilt funtions to creat NumPy array
np.arange(start=0,stop=10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(start=0,stop=1000,step=5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220, 225, 230, 235, 240, 245, 250, 255,
       260, 265, 270, 275, 280, 285, 290, 295, 300, 305, 310, 315, 320,
       325, 330, 335, 340, 345, 350, 355, 360, 365, 370, 375, 380, 385,
       390, 395, 400, 405, 410, 415, 420, 425, 430, 435, 440, 445, 450,
       455, 460, 465, 470, 475, 480, 485, 490, 495, 500, 505, 510, 515,
       520, 525, 530, 535, 540, 545, 550, 555, 560, 565, 570, 575, 580,
       585, 590, 595, 600, 605, 610, 615, 620, 625, 630, 635, 640, 645,
       650, 655, 660, 665, 670, 675, 680, 685, 690, 695, 700, 705, 710,
       715, 720, 725, 730, 735, 740, 745, 750, 755, 760, 765, 770, 775,
       780, 785, 790, 795, 800, 805, 810, 815, 820, 825, 830, 835, 840,
       845, 850, 855, 860, 865, 870, 875, 880, 885, 890, 895, 90

## np.zeros() and np.ones()

Generate arrays of zeros or ones. [[Link](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]

In [14]:
print(np.zeros(10))
print(np.zeros((10,10)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [15]:
print(np.ones(10))
print(np.ones((10,10)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## np.linspace() 
Return evenly spaced numbers over a specified interval. [[Link](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]

In [16]:
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [17]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [18]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## np.eye()

Creates an identity matrix [[Link](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html)]

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Random 
Numpy also has lots of ways to create random number arrays:

## np.random.rand()
Creates an array of the given shape and populates it with random samples from a uniform distribution over ``[0, 1)``. [[Link](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [21]:
np.random.rand(4)

array([0.86357917, 0.46937573, 0.37102701, 0.75543077])

In [22]:
np.random.rand(3,3)

array([[0.65503971, 0.104636  , 0.26757293],
       [0.45753538, 0.51194978, 0.7381371 ],
       [0.42286394, 0.68487043, 0.11689975]])

## np.random.randn()

Returns a sample (or samples) from the "standard normal" distribution [σ = 1]. Unlike **rand** which is uniform, values closer to zero are more likely to appear. [[Link](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]

In [23]:
np.random.randn(4)

array([-0.21248527,  0.54887578, -0.71986914,  1.16705394])

In [24]:
np.random.randn(3,3)

array([[ 1.06244057,  1.16703596, -0.388615  ],
       [ 0.3720199 , -0.79814721, -0.37143494],
       [ 2.40142585,  2.11141046,  0.30818684]])

## np.random.randint()
Returns random integers from `low` (inclusive) to `high` (exclusive).  [[Link](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

In [25]:
np.random.randint(1,1000)

306

In [26]:
np.random.randint(1,1000,50)

array([556, 705, 833, 171, 844, 661, 601, 582, 990, 540, 885, 412, 970,
       457, 105, 594, 512, 833, 631, 865, 834, 345, 511, 256, 871, 689,
       480, 677, 966,  40, 562, 277,   4, 666, 975, 285, 346,  49, 210,
       546, 485, 125, 261, 575, 816, 395, 566, 690, 523,  27], dtype=int32)

## np.random.seed()
Can be used to set the random state, so that the same "random" results can be reproduced. [[Link](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

In [27]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [28]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

## Array Attributes and Methods

Let's discuss some useful attributes and methods for an array:

In [29]:
arr2 = np.arange(36)
randarr = np.random.randint(0,50,10)

In [30]:
print(arr2)
print(randarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
[38 18 22 10 10 23 35 39 23  2]


## Reshape
Returns an array containing the same data with a new shape. [[Link](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [31]:
arr2.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

### max, min, argmax, argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [32]:
randarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2], dtype=int32)

In [33]:
randarr.max()

np.int32(39)

In [34]:
randarr.argmax()

np.int64(7)

In [35]:
randarr.min()

np.int32(2)

In [36]:
randarr.argmin()

np.int64(9)

## Shape

Shape is an attribute that arrays have (not a method):  [[Link](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)]

In [37]:
# Vector
arr2.shape

(36,)

In [38]:
# Notice the two sets of brackets
arr2.reshape(1,36)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35]])

In [39]:
arr2.reshape(1,36).shape

(1, 36)

In [40]:
arr2.reshape(36,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35]])

In [41]:
arr2.reshape(36,1).shape

(36, 1)

## dtype

You can also grab the data type of the object in the array.

In [42]:
arr2.dtype

dtype('int64')

In [43]:
arr3 = np.array([2.5, 3.6, 10.4, 20.5])
arr3.dtype

dtype('float64')

# NumPy Indexing and Selection

In [44]:
import numpy as np

#Creating sample array
arr = np.arange(1,31)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [45]:
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[8])
print(arr[-1])
print(arr[-2])
print(arr[-4])
print(arr[1:10])
print(arr[4:15])

1
2
3
9
30
29
27
[ 2  3  4  5  6  7  8  9 10]
[ 5  6  7  8  9 10 11 12 13 14 15]


## Broadcasting

NumPy arrays differ from normal Python lists because of their ability to broadcast. With lists, you can only reassign parts of a list with new parts of the same size and shape. That is, if you wanted to replace the first 5 elements in a list with a new value, you would have to pass in a new 5 element list. With NumPy arrays, you can broadcast a single value across a larger set of values:

In [46]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30])

In [47]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(1,31)

#Show
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [48]:
#Important notes on Slices
slice_of_arr = arr[5:16]

#Show slice
slice_of_arr

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [49]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [50]:
# Now note the changes also occur in our original array!
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [51]:
## Data is not copied, it's a view of the original array! This avoids memory problems!
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend using the comma notation for clarity.

In [52]:
arr_2d = np.array(([11,12,13],[14,15,16],[17,18,19]))

#Show
arr_2d

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [53]:
#Indexing row
arr_2d[0]

array([11, 12, 13])

In [54]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[0][1]

np.int64(12)

In [55]:
# Getting individual element value
arr_2d[0,1]

np.int64(12)

In [56]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[12, 13],
       [15, 16]])

In [57]:
#Shape bottom row
arr_2d[2]

array([17, 18, 19])

## Conditional Selection

This is a very fundamental concept that will directly translate to pandas later on, make sure you understand this part!

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [58]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [60]:
bool_arr = arr>4

In [61]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [62]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [63]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

## NumPy Arithmetic

You can easily perform *array with array* arithmetic, or *scalar with array* arithmetic. Let's see some examples:

In [65]:
import numpy as np
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [66]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [67]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [68]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [69]:
# This will raise a Warning on division by zero, but not an error!
# It just fills the spot with nan
arr/arr

C:\Users\Vishwajeet\AppData\Local\Temp\ipykernel_14000\205474414.py:3: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [70]:
# Also a warning (but not an error) relating to infinity
1/arr

C:\Users\Vishwajeet\AppData\Local\Temp\ipykernel_14000\616699925.py:2: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [71]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

## Universal Array Functions

NumPy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), or <em>ufuncs</em>, which are essentially just mathematical operations that can be applied across the array.<br>Let's show some common ones:

In [72]:
# Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [73]:
# Calculating exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [74]:
# Trigonometric Functions like sine
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [75]:
# Taking the Natural Logarithm
np.log(arr)

C:\Users\Vishwajeet\AppData\Local\Temp\ipykernel_14000\2367246271.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## Summary Statistics on Arrays

NumPy also offers common summary statistics like <em>sum</em>, <em>mean</em> and <em>max</em>. You would call these as methods on an array.

In [76]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
arr.sum()

np.int64(45)

In [78]:
arr.mean()

np.float64(4.5)

In [79]:
arr.max()

np.int64(9)

## Axis Logic
When working with 2-dimensional arrays (matrices) we have to consider rows and columns. This becomes very important when we get to the section on pandas. In array terms, axis 0 (zero) is the vertical axis (rows), and axis 1 is the horizonal axis (columns). These values (0,1) correspond to the order in which <tt>arr.shape</tt> values are returned.

Let's see how this affects our summary statistic calculations from above.

In [80]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [82]:
arr_2d.shape

(3, 4)

This tells us that <tt>arr_2d</tt> has 3 rows and 4 columns.

In <tt>arr_2d.sum(axis=0)</tt> above, the first element in each row was summed, then the second element, and so forth.

So what should <tt>arr_2d.sum(axis=1)</tt> return?

In [83]:
# THINK ABOUT WHAT THIS WILL RETURN BEFORE RUNNING THE CELL!
arr_2d.sum(axis=1)

array([10, 26, 42])

# Happy Programming!!!